name: mina_weld
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::upython
- conda-forge::jupyter
- conda-forge::matplotlib
- conda-forge::python
- conda-forge::setuptools
- conda-forge::numpy
